/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.CreateContract;
import BLL.CreateTransaction;
import Entities.HopDong;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static org.apache.poi.hssf.usermodel.HeaderFooter.date;
import BLL.CreateTransaction;
import Entities.CanHo;
import Entities.CuDan;
import Entities.DotThanhToan;
import BLL.DotThanhToanBLL;
import Entities.NhanVien;
import java.util.ArrayList;
import javax.swing.JDialog;
import GUI.NhanVienGUI.*;
import javax.swing.JTable;

/**
 *
 * @author Vanh
 */
public class XacNhanThanhToan extends javax.swing.JFrame {

    /**
     * Creates new form XacNhanThanhToan
     */
//    public XacNhanThanhToan() {
//        initComponents();
//        setLocationRelativeTo(null);
//    }
    static CuDan cd = new CuDan();
    static HopDong hd = new HopDong();
    static CanHo ch = new CanHo();
    static NhanVienGUI nvgui = null;
    static NhanVien nv = new NhanVien();

    public static void main(String[] args) {
        CuDan cd = new CuDan("111129", "Nguyễn Việt Anh", "2020-10-10", true, "0222222", "111111", "Hà Nam");
        HopDong hd = new HopDong("020" + Math.random(), "Nguyễn", "2020-20-10", "Thanh Xuan", "001", "HD001", 111111110, 1111110, "2020-01-01", "NV001", 3, 10000000);
        CanHo ch = new CanHo("A10807", 100, 111111110, false, 3, "002", "abc");
        ch.setMaCuDan(cd.getMaCuDan());
        hd.setMaCuDan(cd.getMaCuDan());
        hd.setMaCanHo(ch.getMaCanHo());
        hd.setGia(ch.getGia());
        ch.setTenKhu("ABC");
     //   XacNhanThanhToan xn = new XacNhanThanhToan(cd, hd, ch);
       // xn.setVisible(true);

    }

    public XacNhanThanhToan(CuDan cudan, HopDong hopdong, CanHo canho, NhanVien nvien, NhanVienGUI gui) {
        initComponents();
        setLocationRelativeTo(null);
        cd = cudan;
        hd = hopdong;
        ch = canho;
        nvgui = gui;
        nv = nvien;
        System.out.println("Xac Nhan TT" + canho.toString());
        switch (hd.getSoDot()) {
            case 1:
                Dot2.setVisible(false);
                date2.setVisible(false);
                Tien2.setVisible(false);
                money2.setVisible(false);
                Dot3.setVisible(false);
                date3.setVisible(false);
                Tien3.setVisible(false);
                money3.setVisible(false);
                Dot4.setVisible(false);
                date4.setVisible(false);
                Tien4.setVisible(false);
                money4.setVisible(false);
                Dot5.setVisible(false);
                date5.setVisible(false);
                Tien5.setVisible(false);
                money5.setVisible(false);
                break;
            case 2:
                Dot3.setVisible(false);
                date3.setVisible(false);
                Tien3.setVisible(false);
                money3.setVisible(false);
                Dot4.setVisible(false);
                date4.setVisible(false);
                Tien4.setVisible(false);
                money4.setVisible(false);
                Dot5.setVisible(false);
                date5.setVisible(false);
                Tien5.setVisible(false);
                money5.setVisible(false);
                break;
            case 3:
                Dot4.setVisible(false);
                date4.setVisible(false);
                Tien4.setVisible(false);
                money4.setVisible(false);
                Dot5.setVisible(false);
                date5.setVisible(false);
                Tien5.setVisible(false);
                money5.setVisible(false);
                break;
            case 4:
                Dot5.setVisible(false);
                date5.setVisible(false);
                Tien5.setVisible(false);
                money5.setVisible(false);
                break;
            default:
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKhu4 = new javax.swing.JPanel();
        Dot3 = new javax.swing.JLabel();
        Dot2 = new javax.swing.JLabel();
        Dot1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Tien1 = new javax.swing.JLabel();
        Tien2 = new javax.swing.JLabel();
        Tien3 = new javax.swing.JLabel();
        money3 = new javax.swing.JTextField();
        money1 = new javax.swing.JTextField();
        money2 = new javax.swing.JTextField();
        Dot4 = new javax.swing.JLabel();
        Tien4 = new javax.swing.JLabel();
        money4 = new javax.swing.JTextField();
        Tien5 = new javax.swing.JLabel();
        money5 = new javax.swing.JTextField();
        Dot5 = new javax.swing.JLabel();
        Coc = new javax.swing.JTextField();
        TienCoc = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        date3 = new com.toedter.calendar.JDateChooser();
        date4 = new com.toedter.calendar.JDateChooser();
        date5 = new com.toedter.calendar.JDateChooser();
        date1 = new com.toedter.calendar.JDateChooser();
        jButtonSave = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnKhu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnKhu4.setForeground(new java.awt.Color(0, 90, 227));
        pnKhu4.setPreferredSize(new java.awt.Dimension(326, 237));

        Dot3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Dot3.setForeground(new java.awt.Color(255, 51, 51));
        Dot3.setText("Thời Hạn Đợt 3 :");

        Dot2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Dot2.setForeground(new java.awt.Color(255, 51, 51));
        Dot2.setText("Thời Hạn Đợt 2 :");

        Dot1.setBackground(new java.awt.Color(255, 51, 51));
        Dot1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Dot1.setForeground(new java.awt.Color(255, 51, 51));
        Dot1.setText("Thời Hạn Đợt 1:");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 153, 153));
        jLabel39.setText("DỰ KIẾN THANH TOÁN");

        Tien1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Tien1.setForeground(new java.awt.Color(255, 51, 51));
        Tien1.setText("Số Tiền :");

        Tien2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Tien2.setForeground(new java.awt.Color(255, 51, 51));
        Tien2.setText("Số Tiền :");

        Tien3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Tien3.setForeground(new java.awt.Color(255, 51, 51));
        Tien3.setText("Số Tiền :");

        money3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        money3.setText("0");
        money3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                money3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                money3KeyTyped(evt);
            }
        });

        money1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        money1.setText("0");
        money1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                money1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                money1KeyTyped(evt);
            }
        });

        money2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        money2.setText("0");
        money2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                money2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                money2KeyTyped(evt);
            }
        });

        Dot4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Dot4.setForeground(new java.awt.Color(255, 51, 51));
        Dot4.setText("Thời Hạn Đợt 4 :");

        Tien4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Tien4.setForeground(new java.awt.Color(255, 51, 51));
        Tien4.setText("Số Tiền :");

        money4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        money4.setText("0");
        money4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                money4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                money4KeyTyped(evt);
            }
        });

        Tien5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Tien5.setForeground(new java.awt.Color(255, 51, 51));
        Tien5.setText("Số Tiền :");

        money5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        money5.setText("0");
        money5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                money5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                money5KeyTyped(evt);
            }
        });

        Dot5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Dot5.setForeground(new java.awt.Color(255, 51, 51));
        Dot5.setText("Thời Hạn Đợt 5 :");

        Coc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Coc.setText("0");
        Coc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CocKeyTyped(evt);
            }
        });

        TienCoc.setBackground(new java.awt.Color(255, 51, 51));
        TienCoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TienCoc.setForeground(new java.awt.Color(255, 51, 51));
        TienCoc.setText("Số Tiền Đã Cọc ( Tối thiểu 1%) :");

        date2.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        date2.setMinimumSize(new java.awt.Dimension(116, 35));
        date2.setPreferredSize(new java.awt.Dimension(50, 20));

        date3.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        date3.setPreferredSize(new java.awt.Dimension(50, 20));

        date4.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        date4.setPreferredSize(new java.awt.Dimension(50, 20));

        date5.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        date5.setPreferredSize(new java.awt.Dimension(50, 20));

        date1.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        date1.setMinimumSize(new java.awt.Dimension(116, 35));
        date1.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout pnKhu4Layout = new javax.swing.GroupLayout(pnKhu4);
        pnKhu4.setLayout(pnKhu4Layout);
        pnKhu4Layout.setHorizontalGroup(
            pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhu4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhu4Layout.createSequentialGroup()
                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhu4Layout.createSequentialGroup()
                                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnKhu4Layout.createSequentialGroup()
                                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Dot3)
                                            .addComponent(Dot4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnKhu4Layout.createSequentialGroup()
                                        .addComponent(Dot5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnKhu4Layout.createSequentialGroup()
                                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Dot2)
                                            .addComponent(Dot1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(150, 150, Short.MAX_VALUE)
                                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tien3)
                                    .addComponent(Tien1)
                                    .addComponent(Tien2)
                                    .addComponent(Tien4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhu4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Tien5)))
                        .addGap(32, 32, 32)
                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(money2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(money1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(money3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(money4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(money5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhu4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhu4Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(272, 272, 272))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhu4Layout.createSequentialGroup()
                                .addComponent(TienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Coc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148))))))
        );
        pnKhu4Layout.setVerticalGroup(
            pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhu4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Coc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnKhu4Layout.createSequentialGroup()
                        .addComponent(TienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Dot1)
                        .addComponent(money1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tien1))
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Dot2)
                        .addComponent(Tien2)
                        .addComponent(money2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Dot3)
                        .addComponent(Tien3)
                        .addComponent(money3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(money4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tien4)
                        .addComponent(Dot4)))
                .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhu4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(money5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tien5)))
                    .addGroup(pnKhu4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnKhu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dot5))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_ql.png"))); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_ql.png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKhu4, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKhu4, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonExit))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static String convertJDate(Date input) throws ParseException {
        String strDate = null;
        try {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            strDate = dateFormat.format(input);
        } catch (Exception e) {
            System.out.println("Khong the convert date");
        }
        return strDate;
    }
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {

            ArrayList<String> date = getDate();
            ArrayList<Long> money = getMoney();
            long coc = Long.valueOf(Coc.getText());
            hd.setCoc(coc);
            int error = checkInputError(date);

            if (error == 1) {
                JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra thời hạn các đợt thanh toán !!!");
            }

            if (error == 2) {
                JOptionPane.showMessageDialog(null, "Số tiền cọc tối thiểu là 1%!!!");
            }

            if (error == 0) {
                switch (hd.getSoDot()) {
                    case 1:
                        hd.setThoiHan(convertJDate(date1.getDate()));
                        break;
                    case 2:
                        hd.setThoiHan(convertJDate(date2.getDate()));
                        break;
                    case 3:
                        hd.setThoiHan(convertJDate(date3.getDate()));
                        break;
                    case 4:
                        hd.setThoiHan(convertJDate(date4.getDate()));
                        break;
                    default:
                        hd.setThoiHan(convertJDate(date5.getDate()));
                        break;

                }

                BLL.ThongTinCanHoBLL.updateCH_BLL(hd.getMaCanHo(), hd.getMaCuDan());
                String mahd = BLL.HopDongBLL.insertHD_BLL(hd.getDiaChiKhachHang(), hd.getMaCuDan(), hd.getMaCanHo(), hd.getCoc(), hd.getThoiHan(), hd.getMaNhanVien(), hd.getGia(), hd.getCoc());
                hd.setMaHopDong(mahd);
                for (int i = 0; i < date.size(); i++) {
                    DotThanhToan dtt = new DotThanhToan();
                    dtt.setDotSo(i + 1);
                    dtt.setMaDot(mahd + "." + (i + 1));
                    dtt.setMaHopDong(mahd);
                    dtt.setMaNhanVien(hd.getMaNhanVien());
                    dtt.setSoTienDaTra(0);
                    dtt.setSoTienDuKien(money.get(i));
                    dtt.setThoiHan(convertDateToLong(date.get(i)));
                    boolean insertDTT = DotThanhToanBLL.insert(dtt);
                }
                AutomaticallyClosedMsgBox(1500, "Đang thêm hợp đồng.\nXin hãy đợi....");
                CreateWordFile(date, money);

                // AutomaticallyClosedMsgBox(1000, "Thực hiện mở hợp đồng.\n.....");
                String text = "HopDongMuaBanCanHo_" + mahd + ".docx";
                Desktop.getDesktop().open(new File(text));
                super.dispose();
                nvgui.reloadtblMuaBan();
                nvgui.reloadtblHopDong();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
            System.out.println(ex.getMessage());

        }

    }//GEN-LAST:event_jButtonSaveActionPerformed
    private int checkInputError(ArrayList<String> date) {
        int error = 0;
        try {
            if (hd.getCoc() < hd.getGia() / 100) {
                error = 2;
            }
            for (int i = 0; i < date.size() - 1; i++) {
                if ((long) convertDateToLong(date.get(i)) > (long) convertDateToLong(date.get(i + 1))) {
                    error = 1;
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(XacNhanThanhToan.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        return error;
    }
    private void money2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money2KeyTyped
        // TODO add your handling code here:
        longKeyTyped(evt);
    }//GEN-LAST:event_money2KeyTyped

    private void money3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money3KeyTyped
        // TODO add your handling code here:
        longKeyTyped(evt);
    }//GEN-LAST:event_money3KeyTyped

    private void money4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money4KeyTyped
        // TODO add your handling code here:
        longKeyTyped(evt);
    }//GEN-LAST:event_money4KeyTyped

    private void money5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money5KeyTyped
        // TODO add your handling code here:
        longKeyTyped(evt);
    }//GEN-LAST:event_money5KeyTyped

    private void CocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CocKeyTyped
        // TODO add your handling code here:
        longKeyTyped(evt);
    }//GEN-LAST:event_CocKeyTyped
    private void longKeyTyped(java.awt.event.KeyEvent evt) {
        try {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    private void setFinalMoney() {
        try {
            long coc = 0;
            long Money1 = 0;
            long Money2 = 0;
            long Money3 = 0;
            long Money4 = 0;
            long result;
            switch (hd.getSoDot()) {
                case 1:
                    coc = Long.valueOf(Coc.getText());
                    result = hd.getGia() - coc;
                    if (checkNegativeMoney(result)) {
                        money1.setText("" + result);
                        money1.setEditable(false);
                    }
                    break;
                case 2:
                    coc = Long.valueOf(Coc.getText());
                    Money1 = Long.valueOf(money1.getText());
                    result = hd.getGia() - coc - Money1;
                    if (checkNegativeMoney(result)) {
                        money2.setText("" + result);
                        money2.setEditable(false);
                    }
                    break;
                case 3:
                    coc = Long.valueOf(Coc.getText());
                    Money1 = Long.valueOf(money1.getText());
                    Money2 = Long.valueOf(money2.getText());
                    result = hd.getGia() - coc - Money1 - Money2;
                    if (checkNegativeMoney(result)) {
                        money3.setText("" + result);
                        money3.setEditable(false);
                    }
                    break;
                case 4:
                    coc = Long.valueOf(Coc.getText());
                    Money1 = Long.valueOf(money1.getText());
                    Money2 = Long.valueOf(money2.getText());
                    Money3 = Long.valueOf(money3.getText());
                    result = hd.getGia() - coc - Money1 - Money2 - Money3;
                    if (checkNegativeMoney(result)) {
                        money4.setText("" + result);
                        money4.setEditable(false);
                    }
                    break;
                default:
                    coc = Long.valueOf(Coc.getText());
                    Money1 = Long.valueOf(money1.getText());
                    Money2 = Long.valueOf(money2.getText());
                    Money3 = Long.valueOf(money3.getText());
                    Money4 = Long.valueOf(money4.getText());
                    result = hd.getGia() - coc - Money1 - Money2 - Money3 - Money4;
                    if (checkNegativeMoney(result)) {
                        money5.setText("" + result);
                        money5.setEditable(false);
                    }

                    break;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    private void CocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CocKeyReleased
        // TODO add your handling code here:
        setFinalMoney();
    }//GEN-LAST:event_CocKeyReleased

    private void money2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money2KeyReleased
        // TODO add your handling code here:
        setFinalMoney();
    }//GEN-LAST:event_money2KeyReleased

    private void money3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money3KeyReleased
        // TODO add your handling code here:
        setFinalMoney();
    }//GEN-LAST:event_money3KeyReleased

    private void money4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money4KeyReleased
        // TODO add your handling code here:
        setFinalMoney();
    }//GEN-LAST:event_money4KeyReleased

    private void money5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money5KeyReleased
        // TODO add your handling code here:
        setFinalMoney();
    }//GEN-LAST:event_money5KeyReleased

    private void money1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money1KeyReleased
        // TODO add your handling code here:
        setFinalMoney();
    }//GEN-LAST:event_money1KeyReleased

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void money1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_money1KeyTyped
        // TODO add your handling code here:
        longKeyTyped(evt);
    }//GEN-LAST:event_money1KeyTyped
    private boolean checkNegativeMoney(long num) {
        if (num < 0) {
            JOptionPane.showMessageDialog(null, "Số tiền đã vượt quá giá trị hợp đồng");
            return false;
        } else {
            return true;
        }
    }

    public void CreateWordFile(ArrayList<String> dateDTT, ArrayList<Long> moneyDTT) {
        try {
            CreateContract contract = new CreateContract();
            contract.CreateContract(cd, hd, ch, nv, dateDTT, moneyDTT);
        } catch (Exception ex) {
            Logger.getLogger(NhanVienGUI.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private ArrayList getDate() throws ParseException {
        ArrayList<String> date = new ArrayList<String>();
        try {
            date.add(convertJDate(date1.getDate()));
            date.add(convertJDate(date2.getDate()));
            date.add(convertJDate(date3.getDate()));
            date.add(convertJDate(date4.getDate()));
            date.add(convertJDate(date5.getDate()));

            for (int i = 4; i > -1; i--) {
                if (date.get(i) == null) {
                    date.remove(date.get(i));
                }
            }

        } catch (Exception e) {
            System.out.println("Error in getDate()" + e.getMessage());
        }
        return date;

    }

    private ArrayList getMoney() throws ParseException {
        ArrayList<Long> money = new ArrayList<Long>();
        try {
            money.add(Long.valueOf(money1.getText()));
            money.add(Long.valueOf(money2.getText()));
            money.add(Long.valueOf(money3.getText()));
            money.add(Long.valueOf(money4.getText()));
            money.add(Long.valueOf(money5.getText()));
            System.out.println(money.size());
            for (int i = 4; i > -1; i--) {
                if (money.get(i) == 0) {
                    money.remove(money.get(i));
                }
            }

        } catch (Exception e) {
            System.out.println("Error in getMoney()" + e.getMessage());
        }
        return money;

    }

    public void AutomaticallyClosedMsgBox(long time, String text) {
        JOptionPane jop = new JOptionPane();
        jop.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        jop.setMessage(text);
        JDialog dialog = jop.createDialog(null, "Thông báo");

        // Set timer
        new Thread(() -> {
            try {
                Thread.sleep(time);
            } catch (InterruptedException e) {
                System.out.println(e);
            }
            dialog.dispose();
        }).start();

        dialog.setVisible(true);
    }

    public static Long convertDateToLong(String string_date) throws ParseException {
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date = (Date) formatter.parse(string_date);
        long mills = date.getTime();
        return mills;
    }
    public String addDelimitorRealTime(String SoTien){
            String SoTienGD = addDelimitor(removeDelimitor(SoTien.trim()));
            return SoTienGD;
    }
     private String addDelimitor(Long number) {
        String numberInText = String.valueOf(number);

        int numberLength = numberInText.length();

        if (numberLength < 4) {
            return numberInText;
        }

        StringBuilder sb = new StringBuilder("");

        for (int i = 0, j = numberLength % 3 == 0 ? 3 : numberLength % 3; i < numberLength; ++i) {

            if (j < numberLength && i == j) {
                sb.append(".");
                j += 3;
            }

            sb.append(numberInText.charAt(i));
        }

        return sb.toString();
    }

    private Long removeDelimitor(String number) {
        return Long.parseLong(number.replaceAll("\\.", ""));
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Coc;
    private javax.swing.JLabel Dot1;
    private javax.swing.JLabel Dot2;
    private javax.swing.JLabel Dot3;
    private javax.swing.JLabel Dot4;
    private javax.swing.JLabel Dot5;
    private javax.swing.JLabel Tien1;
    private javax.swing.JLabel Tien2;
    private javax.swing.JLabel Tien3;
    private javax.swing.JLabel Tien4;
    private javax.swing.JLabel Tien5;
    private javax.swing.JLabel TienCoc;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private com.toedter.calendar.JDateChooser date3;
    private com.toedter.calendar.JDateChooser date4;
    private com.toedter.calendar.JDateChooser date5;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JTextField money1;
    private javax.swing.JTextField money2;
    private javax.swing.JTextField money3;
    private javax.swing.JTextField money4;
    private javax.swing.JTextField money5;
    private javax.swing.JPanel pnKhu4;
    // End of variables declaration//GEN-END:variables
}
